name: Factions
version: ${factions.desc}
main: com.massivecraft.factions.FactionsPlugin
authors: [Olof Larsson, Brett Flannigan, drtshock, dariasc, CmdrKittens, mbaxter, Theo Bong]
loadbefore: [Gonzo]
api-version: 1.8
commands:
  factions:
    description: Reference command for Factions.
    aliases: [f]